<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TheLogsAreWrong.Domain</AssemblyName>
    <RootNamespace>TheLogsAreWrong</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TheLogsAreWrong.PortableAuthority\TheLogsAreWrong.PortableAuthority.csproj" />
  </ItemGroup>
</Project>
