using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Tlaw.AgentProtocol;

namespace Tlaw.Dispatcher;

public static class IngestHandoffCommand
{
    public static int Run(string[] args, TextWriter output, TextWriter error) => Run(args, output, error, new SystemLeaseClock());
    internal static int RunForTesting(string[] args, TextWriter output, TextWriter error, ILeaseClock clock) => Run(args, output, error, clock);
    private static int Run(string[] args, TextWriter output, TextWriter error, ILeaseClock clock)
    {
        try
        {
            var options = HandoffIngestionOptions.Parse(args); IngestionPathGuard.ValidateOutput(options.OutputPath, options.StorePath, options.TaskPath, options.HandoffPath);
            var registry = PacketSchemaRegistry.Load(Path.Combine(TaskPacketCommand.FindRepositoryRoot(), "docs", "agent", "schemas")); var task = Task(options.TaskPath, registry); var handoff = Handoff(options.HandoffPath, registry);
            Correlate(task, handoff.Packet); var status = options.Reason == "timeout" ? LocalLeaseStatus.Expired : LocalLeaseStatus.Active; var decision = handoff.Packet.RequiredString("status") == "ready" ? "reassign" : "human"; var bytes = HandoffIngestionJson.Write(task, handoff.Packet, Convert.ToHexStringLower(SHA256.HashData(handoff.Bytes)), status, options.Reason, decision);
            FileLeaseStore.WithMatchingLeaseStateGuard(options.StorePath, task.TaskId, task.ClaimedBy, task.ClaimId, status, clock, recheck => { HandoffIngestionJson.Validate(bytes); recheck(); TaskPacketCommand.WriteAtomically(options.OutputPath, bytes); return 0; });
            try { output.WriteLine($"HANDOFF: {decision}"); } catch (Exception ex) when (ex is IOException or ObjectDisposedException or InvalidOperationException or NotSupportedException) { error.WriteLine("FAIL: handoff ingestion record was already published."); return 1; }
            return 0;
        }
        catch (Exception ex) when (ex is HandoffIngestionException or IngestResultCommandException or LeaseStoreException or IOException or UnauthorizedAccessException or DirectoryNotFoundException or ArgumentException or DecoderFallbackException or InvalidDataException or JsonException) { error.WriteLine($"FAIL: {ex.Message}"); return 1; }
        catch { error.WriteLine("FAIL: handoff ingestion failed unexpectedly."); return 1; }
    }
    private static TaskV2Packet Task(string path, PacketSchemaRegistry r) { var v = PacketValidator.Validate(TaskPacketCommand.ReadUtf8(path), r); if (!v.IsValid || v.Packet?.Schema != "tlaw.agent-task/v2") throw new HandoffIngestionException("Input task must be valid tlaw.agent-task/v2."); var t = TaskV2Packet.From(v.Packet); return t.IsClaimed ? t : throw new HandoffIngestionException("Input task must be fully claimed."); }
    private static (ProtocolPacket Packet, byte[] Bytes) Handoff(string path, PacketSchemaRegistry r) { var b = File.ReadAllBytes(path); var v = PacketValidator.Validate(new UTF8Encoding(false, true).GetString(b), r); if (!v.IsValid || v.Packet?.Schema != "tlaw.agent-handoff/v2") throw new HandoffIngestionException("Input handoff must be valid tlaw.agent-handoff/v2."); return (v.Packet, b); }
    private static void Correlate(TaskV2Packet t, ProtocolPacket h) { if (!string.Equals(t.TaskId,h.RequiredString("task_id"),StringComparison.Ordinal)||!string.Equals(t.SourceId,h.RequiredString("source_id"),StringComparison.Ordinal)||!string.Equals(t.ClaimedBy,h.RequiredString("claimed_by"),StringComparison.Ordinal)||!string.Equals(t.ClaimId,h.RequiredString("claim_id"),StringComparison.Ordinal)||!string.Equals(t.BaseSha,h.RequiredString("base_sha"),StringComparison.Ordinal)||!string.Equals(t.Worktree,h.RequiredString("branch"),StringComparison.Ordinal)) throw new HandoffIngestionException("Handoff identity does not exactly match the claimed task."); }
}
public sealed class HandoffIngestionException(string message) : Exception(message);
internal sealed record HandoffIngestionOptions(string TaskPath,string HandoffPath,string StorePath,string Reason,string OutputPath)
{ internal static HandoffIngestionOptions Parse(IReadOnlyList<string> a) { if(a.Count!=11||a[0]!="ingest-handoff") throw new HandoffIngestionException("Handoff ingestion requires exactly five named options."); var d=new Dictionary<string,string>(StringComparer.Ordinal); for(var i=1;i<a.Count;i+=2) if(!d.TryAdd(a[i],a[i+1])||string.IsNullOrWhiteSpace(a[i+1])) throw new HandoffIngestionException("Handoff ingestion received an unknown, duplicate, or empty option."); if(!d.TryGetValue("--task",out var t)||!d.TryGetValue("--handoff",out var h)||!d.TryGetValue("--lease-store",out var s)||!d.TryGetValue("--reason",out var r)||!d.TryGetValue("--output",out var o)||d.Count!=5||!Path.IsPathFullyQualified(s)||r is not ("timeout" or "quota_exhaustion" or "manual_cancel")) throw new HandoffIngestionException("Handoff ingestion options or reason are invalid."); return new(Path.GetFullPath(t),Path.GetFullPath(h),Path.GetFullPath(s),r,Path.GetFullPath(o)); } }
internal static class HandoffIngestionJson
{ internal static string Write(TaskV2Packet t,ProtocolPacket h,string hash,LocalLeaseStatus status,string reason,string decision) { var blocked=decision=="human"?"true":"false"; return $"{{\n  \"schema\": \"tlaw.dispatcher-handoff-ingestion/v1\",\n  \"task_id\": {JsonSerializer.Serialize(t.TaskId)},\n  \"source_id\": {JsonSerializer.Serialize(t.SourceId)},\n  \"claimed_by\": {JsonSerializer.Serialize(t.ClaimedBy)},\n  \"claim_id\": {JsonSerializer.Serialize(t.ClaimId)},\n  \"handoff_sha256\": \"{hash}\",\n  \"handoff_status\": {JsonSerializer.Serialize(h.RequiredString("status"))},\n  \"head_sha\": {JsonSerializer.Serialize(h.RequiredString("head_sha"))},\n  \"branch\": {JsonSerializer.Serialize(t.Worktree)},\n  \"lease_status\": \"{status.ToString().ToLowerInvariant()}\",\n  \"lease_action\": \"release_required\",\n  \"release_reason\": \"{reason}\",\n  \"decision\": \"{decision}\",\n  \"next_state\": \"todo\",\n  \"blocked\": {blocked}\n}}\n"; }
  internal static void Validate(string text) { using var d=JsonDocument.Parse(new UTF8Encoding(false,true).GetBytes(text)); var r=d.RootElement; var names=new[]{"schema","task_id","source_id","claimed_by","claim_id","handoff_sha256","handoff_status","head_sha","branch","lease_status","lease_action","release_reason","decision","next_state","blocked"}; var seen=new HashSet<string>(); if(r.ValueKind!=JsonValueKind.Object||r.EnumerateObject().Any(p=>!seen.Add(p.Name)||!names.Contains(p.Name,StringComparer.Ordinal))||seen.Count!=names.Length||names.Any(n=>!seen.Contains(n))) throw new HandoffIngestionException("Generated handoff ingestion record is invalid."); string S(string n)=>r.TryGetProperty(n,out var v)&&v.ValueKind==JsonValueKind.String&&!string.IsNullOrWhiteSpace(v.GetString())?v.GetString()!:throw new HandoffIngestionException("Generated handoff ingestion record is invalid."); var hash=S("handoff_sha256"); var head=S("head_sha"); var status=S("handoff_status"); var lease=S("lease_status"); var reason=S("release_reason"); var decision=S("decision"); if(S("schema")!="tlaw.dispatcher-handoff-ingestion/v1"||S("lease_action")!="release_required"||S("next_state")!="todo"||hash.Length!=64||hash.Any(c=>!(c is >= '0' and <= '9' or >= 'a' and <= 'f'))||head.Length!=40||head==new string('0',40)||head.Any(c=>!(c is >= '0' and <= '9' or >= 'a' and <= 'f'))||status is not ("ready" or "blocked")||lease is not ("active" or "expired")||reason is not ("timeout" or "quota_exhaustion" or "manual_cancel")||decision is not ("reassign" or "human")||r.GetProperty("blocked").ValueKind is not (JsonValueKind.True or JsonValueKind.False)|| (status=="ready" && (decision!="reassign"||r.GetProperty("blocked").GetBoolean())) || (status=="blocked" && (decision!="human"||!r.GetProperty("blocked").GetBoolean())) || (reason=="timeout"&&lease!="expired") || (reason!="timeout"&&lease!="active")) throw new HandoffIngestionException("Generated handoff ingestion record is invalid."); } }
